name: Builder

on:
  push:
    branches:
      - main

jobs:
  mac-builder:
    name: macOS Builder
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache macOS Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            $GITHUB_WORKSPACE/SourcePackages
            $GITHUB_WORKSPACE/macos_build
            /Users/runner/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build macOS
        run: make macos

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: barcelona
          path: Build/macOS/Build/Products/Release/barcelona-mautrix-macOS/
